### PR TITLE
Issue 190

### PR DESCRIPTION
**Pull request by carmelopellegrino**
solves issue #190.

### CODE REVIEW

**Comment by marcodeltutto** [comment]
Hi Carmelo, looks good to me but when I run this on my Pi I can't see the I: label that should be next to I:E. Maybe we can split the label that contains both I:E and I:? This is how it looks:

IMG_3936

**Comment by carmelopellegrino** [comment]
Hi Marco! There is a possibility that raspbian doesn't ship by default the correct font and replace with a similar sans-serif one. Can you please check that the `fonts-cantarell` package is installed

**Comment by marcodeltutto** [comment]
Hi Carmelo! This is how it looks like after having installed the Cantarell font on my Pi: 

IMG_3937

**Comment by carmelopellegrino** [comment]
Hi Marco,
cool, there is still a column sign hidden :angry:

**Comment by carmelopellegrino** [comment]
I've split the label into two, so that the `1 :` text should be always visible

**Comment by carmelopellegrino** [comment]
I would tentatively merge this PR. I've tested the new code on my RPI2 with the official raspbian image and here is a picture
foto

**Pull request merged**
