### PR TITLE
Issue 199

### LINKED ISSUE #199: Reading settings parameters when the GUI starts
When the GUI starts, this is the current behavior in terms of reading the settings parameters from the ESP:
- if the ESP is ventilating, read the ESP parameters and update the settings panels accordingly
- if the ESP is not ventilating, do not read the current settings parameters, and the settings panels display the default ones read from the yaml file.
This is done in `controller_status.py`, method `_init_settings_panel()`.

Is this what we want? Or do we want to always read the current ESP parameters and update the settings panels accordingly?

The above design has a problem: if the ESP has a RR of, say, 15, and it is not ventilating, when the GUI starts the GUI will display a RR of 12, but it will never set this 12 to the ESP. So at the next Start, the ESP starts ventilation with RR=15, even if the GUI says 12.

### PR DESCRIPTION
**Pull request by marcodeltutto**
Fixes #199 
Adds a method called `_init_settings_panel` to `StartStopWorker` class.
This method is only called at initialization. 
It checks if the ESP is running or not and:
- If the ESP is NOT running, it sets the YAML default values to the ESP
- If the ESP is running, it reads the ESP values and sets them to the setting panel

If the user then clicks on `Resume Ventilation` then the settings are loaded from the settings.txt.

### CODE REVIEW

**Comment by carmelopellegrino** [comment]
Ciao Marco! There here are some problems:
- if `run == 0` the settings from the YAML file are automatically and immediately set without waiting for the user to click on `New patient` or `Resume ventilation`
- the settings from the JSON file are ignored
- is `run == 1` the settings are none of that present in the YAML, JSON or FakeESP32 (where are them stored?!?), and are always different (e.g. PCV::RR is 60 and relaunching it is 12!)

**Comment by marcodeltutto** [comment]
Hi Carmelo!

1. True. If `run==0`, the settings from the YAML file are loaded at init time. But if you then click on `Resume ventilation` it will load the settings from the JSON file. This is what we discussed yesterday, but we can revisit of course.
2. I don't see them ignored if I click on `Resume ventilation`.
3. If `run==1`, it reads the current ESP settings, in our case from the FakeESP32. The FakeESP32 generates random settings every time is called (see L249 of `fake_esp32serial.py`), hence the different numbers. We may change this behavior in the FakeESP32.

**Comment by carmelopellegrino** [comment]
Ciao Marco!
1. you are right! My bad with the test!
2. true again, sorry!
3. got it! I'm going to change this to have a reproducible test.

Thanks!

**Comment by carmelopellegrino** [comment]
I've added the ESP parameters to the `set_params` dictionary and provided conversion for the ratio parameter read from ESP.
@marcodeltutto, can you please double check that everything is fine?

**Comment by marcodeltutto** [comment]
Everything looks fine to me!

**Pull request merged**
