### PR TITLE
Issue 90

### LINKED ISSUE #90: add initial, start and alarm settings pages
- [x] add a fullscreen page, called the `initial` page, with two buttons:
    - `New patient`: this loads a default presets settings parameter (that used in ventilation)
    - `Resume ventilation`: this loads the settings used during the last ventilation
then both buttons move the GUI to the `start` page.
- [ ] add a fullscreen page, called the `start` page, with the following buttons:
    - `Start ventilation`: goes to the `home` page (that with plots)
    - `Settings`: goes to the `settings` page
    - `Circuit test`: issues the command (TBD) to the ESP32 to start a test procedure and then report about the results (TBD)
   moreover, there should be a `PEEP` monitor that updates every 0.2 secs or less its value asking to the hardware.
- [x] add a fullscreen page called `alarm settings` that allows to set threshold values (minimum and maximum) for the monitored observables  

this issue is better addressed right after the solution of issue #89

### PR DESCRIPTION
**Pull request by javerom**
Fixes #90 
All infrastructure changes have been made, but the following functionality still needs to be implemented:
- Limits changes on alarms
- Switching monitors/plot with main window
- ESP circuit test
- JSON current config file
- change stats on monitor (optional)

### CODE REVIEW

**Comment by javerom** [comment]
Pause buttons have been moved back to main menu. Settings now have two options: mode and alarms

**Comment by carmelopellegrino** [comment]
I've found the following a problem:
- go to the home page
- plots are ok
- freeze
- wait 1-2 secs
- go back
- the plot x-axes are all shifted!
issue-90

**Comment by javerom** [comment]
Yup that's bad. Looks like it was a always a problem in frozen_plots.py (with autoRange), but now that things are dynamic, the default auto is off. Can be fixed.

**Comment by javerom** [comment]
Fixed with 5a83ddb8af44104800db97d1d48f4270496a1624

**Pull request merged**
