### PR TITLE
fixing mock.ino

### PR DESCRIPTION
**Pull request by guescio**
Fixed Time namespace. Removed unused from_millis.

### CODE REVIEW

**Comment by carmelopellegrino** [comment]
Ciao Francesco, can you explain why lower-case namespaces are to be fixed? And why you removed a _currently unused_ function?

**Comment by guescio** [comment]
Ciao Carmelo! Nothing against lowercase namespaces but compilation fails due to redeclaration of `time`. The `from_millis` function looked like a stray function since `from_micros` is used. It can be put back if part of a bigger plan. :) What do you suggest?

**Comment by carmelopellegrino** [comment]
Ah OK I'm used to the [Google Style Guides for C++](https://google.github.io/styleguide/cppguide.html#Namespaces) where lower-case namespaces seem to be preferred. A different name may solve the issue. No idea at the moment and suggestions are welcome.
I'm using a different C++ standard library implementation that doesn't have any clash with `time`.`from_millis` is there because during long tests `micros` may wrap and `millis` can play a role. Further, the intent was to partly copy `std::chrono`, which is not present in my version of the STL.

Maybe it's time to update my Arduino IDE distribution and libraries but I didn't have the time to do and really needed to make tests against my Arduino UNO. Maybe in some days, when the situation will be relaxed, I'll have the time to reinstall from scratch, but for the time being I would keep it as it is.

**Comment by guescio** [comment]
Good points! Agreed, this is definitely not urgent.

**Comment by carmelopellegrino** [comment]
modifications carried on in issue #167

**Pull request closed without merging**
